{% set name = "wincertstore" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: ebd681f45f4e156493b4fa54f134b9a171d9c0a8de40ae1a0bc96c3092cb8b12

build:
  number: 0
  skip: true  # [not win]
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/tiran/wincertstore
  license: PSF 2
  license_file: LICENSE
  summary: Python module to extract CA and CRL certs from Windows' cert store (ctypes based).

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - ocefpaf
