travis:
  secure:
    BINSTAR_TOKEN: gudDoK7QTbemF6pFaya5Ybq/5sxBG436OR93pcm5+A0PcEBieEyo8qqNCYOS7zqRtEUAozC2Co26A4r9URE0ce0B/vu02zdNj708ahG8nLATtxYzlDfT7jcrh5ZixAVBaIugxVIAnqvcoVpwf3qmdN74gYjpABpimI98UhH3Mp00Kn66rWemj5Hl5eRV3Ragu13CU+I7Yjl3pnEo8Z4RJN5j0xjQo3ksr5dpsASditS6N/7uEFWpJFiaGbKKVwi7HtYBlB65sbW18RtLnV3u8/wUN4/JQh3dmyACTcrjnV2MwWIf2UiX+JXKx29O6UXDL1C5UmZWcIv5ypH/HkS1YlSErUDubSt83sjN3PHwVliO/lrp1L25pHxXHjRiYGyoCRw2/swpV996/HTaLlh25JYNa9/R0+CJeoFKg7CKggTy+XCtv1neHZ7rKbIkD6T1nBNkhYPrUj4hzFOTsPN7k/zx5TilAhs901GCNi4DJvQIrCSsMGEcsSRyQkuPtbu/HyGJmViKptK3uHZuOxs3qwIRUlI4PD3r1UyQFTosBotJFsnwsSbyh5xSR1kOVJzVQiTBDpFqwYGJEeV9BboS0H/+WltzaxQ1ZwZ1cnHDnCHu1EZOPIWclqXjGwssqMc5eGqhYtbnOe1HI9l4VFsdjAqXElgW9anzOq7Y0iHkRtc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
