travis:
  secure:
    BINSTAR_TOKEN: qmjHqJjqS/Cj3b3H9JKISNy8tlidl1VfRsrAx/6RlEg3ebOYt4KHKx1ga9/KVnNFIO/bEIBpUjAabcMXHjUu3vdsxzfnGihjheyvr1jRJ90tmtTCj8cPDRSr+OTttK6SAfbmsOFI+ZBwMD5los7XZ/nVGABcrymQC6YRMh4q+/ztTRvD0Iijjq4ujRcQsHReVCwn+PqzOghwN+/q2fEEBOI8ckJPhAEyr4o2ZYI3XjzVnRuoRRlGtz0wt9L8/xJT0c8BxpCEVY0IlbU/m+1SEsyxO6Px9bnQWJjdtsrNnbK+pRrsOfHx2pK9of7gz0vggGn11gWOir7MbVmXbpqU5Vczzso1YP5gO9cuFl76v88oFHZFte+OtEBizhTjara7zabCWidmKBrW2AWBTG4737w4R9gJNbdxSKvfn7mN/mxObFchSVMvMXW1dA40EdlI+koLbLo+SoyKgiCqHb6kehmrUyrLc/GTKfjVvt/d/rfAZP/jO2mVumCtoxnHoJPHsx0LirzqeG43ju9BKejiRbITY+B7B78xxlkVmJgJ+t2d55QjnUEmgfsIW4+B860Vg2JN9FnDj5wpvX4ozJnzKWgdzsXhP8rQmWLrzArpkgsHQtTQIlI1Ue+nRQx+3siYXF7MiejB2/OerJ2tGuqruogKndOr1jukIIIv31RB7dM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
